name: Python CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure using v3 for the latest features
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v4  # Ensure using v4 for the latest features
        with:
          python-version: '3.9'  # Use Python 3.9, adjust as needed

      - name: Check Python version
        run: python --version

      - name: Check out the directory contents before setting up venv
        run: ls -la

      - name: Remove existing virtual environment if any
        run: |
          if [ -d "venv" ]; then rm -rf venv; fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          echo "Directory contents after creating venv:"
          ls -la
          source venv/bin/activate
          echo "Directory contents after activating venv:"
          ls -la
          which python
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest src/tests
        env:
          CI: true

      # - name: Lint with flake8
      #   run: |
      #     source venv/bin/activate
      #     pip install flake8
      #     flake8 src

      - name: Debugging Information
        run: |
          df -h
          free -m
          uname -a
          env
          cat /etc/hosts

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token
          heroku whoami

      - name: Configure Heroku Git remote with authentication
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/market-mood.git
          git remote -v

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git push heroku HEAD:main -f
