name: Python CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: macos-latest  # Use macOS as the platform for local simulation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure using v3 for the latest features

      - name: Set up Python
        uses: actions/setup-python@v4  # Ensure using v4 for the latest features
        with:
          python-version: '3.9'  # Use Python 3.9, adjust as needed

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest src/tests
        env:
          CI: true

      # - name: Lint with flake8
      #   run: |
      #     source venv/bin/activate
      #     pip install flake8
      #     flake8 src

      - name: Debugging Information
        run: |
          df -h
          vm_stat
          uname -a
          env
          cat /etc/hosts

      - name: Install Heroku CLI
        uses: akhileshns/heroku-cli-action@v1.0.0

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token
          heroku whoami

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/market-mood-8e528490197d.git
          git push heroku HEAD:main -f
