name: Python CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the platform for local simulation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure using v3 for Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v4  # Ensure using v4 for Node.js 20
        with:
          python-version: '3.9'  # Use Python 3.9, adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest src/tests
        env:
          CI: true

      - name: Lint with flake8
        run: |
          . venv/bin/activate
          pip install flake8
          flake8 src

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "market-mood"  # Replace with your Heroku app name
          heroku_email: "mreed5812@gmail.com"   # Replace with your Heroku account em
