name: Python CI/CD

on:
  push:
    branches:
      - main  # Replace with your main branch name
  pull_request:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: macos-latest  # Use macOS as the platform for local simulation

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure using v3 for the latest features

      - name: Set up Python
        uses: actions/setup-python@v4  # Ensure using v4 for the latest features
        with:
          python-version: '3.9'  # Use Python 3.9, adjust as needed

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m venv venv
          ls -al venv/bin
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest src/tests
        env:
          CI: true

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          pip install flake8
          flake8 src

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "market-mood"  # Replace with your Heroku app name
          heroku_email: "mreed5812@gmail.com"  # Replace with your Heroku account email
